/**
 * digest.js
 * Generates a weekly neighborhood digest.
 * Output: stdout + digests/YYYY-MM-DD.md
 *
 * Sections:
 *   1. New 311 requests this week (by category)
 *   2. Overdue open requests (>30 days, by type)
 *   3. Commitments due for follow-up (past due or within next 14 days)
 *   4. Quick stats
 */

const fs = require('fs');
const path = require('path');
const { getDb } = require('./db');

function today() {
  return new Date().toISOString().slice(0, 10);
}

function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

function daysFromNow(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

function groupBy(rows, key) {
  const map = {};
  for (const r of rows) {
    const k = r[key] || 'Unknown';
    map[k] = (map[k] || 0) + 1;
  }
  return Object.entries(map).sort((a, b) => b[1] - a[1]);
}

function formatDate(d) {
  return d ? d.slice(0, 10) : '—';
}

function buildDigest(db) {
  const lines = [];
  const dateStr = today();

  lines.push(`# West Waldo Neighborhood Digest — ${dateStr}`);
  lines.push('');
  lines.push('> Generated by NeighborhoodOS · Data: KC Open Data 311 + local commitment log');
  lines.push('');

  // ── Section 0a: Upcoming City Meetings (next 14 days) ──
  const in14 = daysFromNow(14);
  try {
    const meetings = db.prepare(`
      SELECT event_date, body_name, event_location, agenda_file
      FROM civic_meetings
      WHERE date(event_date) BETWEEN date('now') AND date(?)
      ORDER BY event_date ASC
    `).all(in14);

    lines.push('## 📅 Upcoming City Meetings (next 14 days)');
    if (meetings.length === 0) {
      lines.push('No meetings scheduled in the next 14 days. Run fetch-meetings.js to update.');
    } else {
      for (const m of meetings) {
        const d = formatDate(m.event_date);
        const loc = (m.event_location || 'Location TBD').slice(0, 60);
        const agenda = m.agenda_file ? ' [agenda available]' : '';
        lines.push(`- **${d}** | ${m.body_name}${agenda}`);
        lines.push(`  _${loc}_`);
      }
    }
    lines.push('');
  } catch (e) {
    // table not yet created
  }

  // ── Section 0b: Policy Flags - Legislation touching this area ──
  try {
    const flags = db.prepare(`
      SELECT pf.flag_reason, pf.flagged_at, l.matter_type, l.title, l.status, l.intro_date, l.sponsor
      FROM policy_flags pf
      JOIN legislation l ON l.matter_id = pf.source_id
      WHERE pf.source = 'legislation'
      ORDER BY l.intro_date DESC
      LIMIT 10
    `).all();

    lines.push('## ⚠️ Policy Flags: Legislation Touching This Area');
    if (flags.length === 0) {
      lines.push('No flagged legislation found. Run fetch-meetings.js + ingest-meetings.js.');
    } else {
      for (const f of flags) {
        const title = (f.title || 'Untitled').slice(0, 100).replace(/\n/g, ' ');
        const sponsor = f.sponsor ? f.sponsor.replace(/\n/g, ' ').slice(0, 60) : 'Unknown';
        lines.push(`- **[${f.matter_type}]** ${title}`);
        lines.push(`  Status: ${f.status || '?'} | Matched: _${f.flag_reason}_ | ${formatDate(f.intro_date)}`);
      }
    }
    lines.push('');
  } catch (e) {
    // table not yet created
  }

  // ── Section 1: New this week ──
  const weekAgo = daysAgo(7);
  const newRequests = db.prepare(`
    SELECT category, request_type, type, status, creation_date, street_address
    FROM requests_311
    WHERE creation_date >= ?
    ORDER BY creation_date DESC
  `).all(weekAgo);

  lines.push('## 🆕 New 311 Requests This Week');
  if (newRequests.length === 0) {
    lines.push('No new requests in the past 7 days.');
  } else {
    lines.push(`${newRequests.length} new request(s) filed since ${weekAgo}:`);
    lines.push('');
    const byCategory = groupBy(newRequests, 'category');
    for (const [cat, count] of byCategory) {
      lines.push(`- **${cat}**: ${count}`);
    }
    lines.push('');
    lines.push('Recent requests:');
    for (const r of newRequests.slice(0, 15)) {
      const label = r.category || r.request_type || r.type || 'Unknown';
      lines.push(`  - [${formatDate(r.creation_date)}] ${label} — ${r.street_address || 'Unknown address'} (${r.status || '?'})`);
    }
  }
  lines.push('');

  // ── Section 2: Overdue open requests (>30 days) ──
  // KC Open Data uses abbreviated status codes: OPEN, ASSIG (assigned), RESOL (resolved),
  // CANC (cancelled), DUP (duplicate). We treat OPEN + ASSIG as still-open.
  const thirtyDaysAgo = daysAgo(30);
  const overdue = db.prepare(`
    SELECT case_id, category, request_type, type, creation_date, street_address, status
    FROM requests_311
    WHERE status IN ('OPEN', 'ASSIG', 'Open', 'open', 'Assigned', 'assigned')
      AND creation_date <= ?
    ORDER BY creation_date ASC
  `).all(thirtyDaysAgo);

  lines.push('## ⚠️ Overdue Open Requests (>30 days)');
  if (overdue.length === 0) {
    lines.push('No overdue open requests. 🎉');
  } else {
    lines.push(`${overdue.length} request(s) open for more than 30 days:`);
    lines.push('');
    const byType = groupBy(overdue, 'category');
    for (const [cat, count] of byType) {
      lines.push(`- **${cat}**: ${count}`);
    }
    lines.push('');
    lines.push('Longest-waiting:');
    for (const r of overdue.slice(0, 10)) {
      const label = r.category || r.request_type || r.type || 'Unknown';
      const openDays = Math.floor((Date.now() - new Date(r.creation_date)) / 86400000);
      lines.push(`  - [${openDays}d] ${label} — ${r.street_address || 'Unknown'} (${r.case_id})`);
    }
  }
  lines.push('');

  // ── Section 3: Commitments due ──
  const twoWeeksOut = daysFromNow(14);
  const todayStr = today();

  const commitmentsDue = db.prepare(`
    SELECT id, official_name, role, meeting_date, commitment_text, follow_up_date
    FROM commitments
    WHERE status = 'open'
      AND (follow_up_date <= ? OR follow_up_date IS NULL)
    ORDER BY follow_up_date ASC
  `).all(twoWeeksOut);

  lines.push('## 📋 Commitments Needing Attention');
  if (commitmentsDue.length === 0) {
    lines.push('No commitments due in the next 14 days.');
  } else {
    for (const c of commitmentsDue) {
      const overdueMark = c.follow_up_date && c.follow_up_date < todayStr ? ' ← **OVERDUE**' : '';
      lines.push(`- **#${c.id} — ${c.official_name}** (${c.role || 'unknown role'})`);
      lines.push(`  Meeting: ${formatDate(c.meeting_date)} | Follow-up: ${formatDate(c.follow_up_date)}${overdueMark}`);
      lines.push(`  > ${c.commitment_text}`);
      lines.push('');
    }
  }
  lines.push('');

  // ── Section 4: Quick stats ──
  const total = db.prepare("SELECT COUNT(*) AS n FROM requests_311").get().n;
  const open  = db.prepare("SELECT COUNT(*) AS n FROM requests_311 WHERE status IN ('OPEN','ASSIG','Open','open','Assigned','assigned')").get().n;
  const closed = db.prepare("SELECT COUNT(*) AS n FROM requests_311 WHERE status IN ('RESOL','CANC','DUP','Closed','Resolved','closed','resolved','Cancelled','cancelled')").get().n;

  // Avg resolution time — KC's days_open field tells us how long each request was open.
  const avgResol = db.prepare(`
    SELECT AVG(days_open) AS avg_days, COUNT(*) AS n
    FROM requests_311
    WHERE status IN ('RESOL','Closed','Resolved','closed','resolved')
      AND days_open IS NOT NULL
      AND days_open >= 0
  `).get();
  const avgResolDays = avgResol && avgResol.n > 0 ? Math.round(avgResol.avg_days) : null;

  const totalCommitments = db.prepare("SELECT COUNT(*) AS n FROM commitments").get().n;
  const openCommitments  = db.prepare("SELECT COUNT(*) AS n FROM commitments WHERE status='open'").get().n;

  // Oldest open request
  const oldest = db.prepare(`
    SELECT creation_date FROM requests_311
    WHERE status IN ('OPEN','ASSIG','Open','open','Assigned','assigned')
    ORDER BY creation_date ASC LIMIT 1
  `).get();
  const oldestDays = oldest
    ? Math.floor((Date.now() - new Date(oldest.creation_date)) / 86400000)
    : null;

  lines.push('## 📊 Quick Stats');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total 311 requests (Waldo) | ${total} |`);
  lines.push(`| Open requests | ${open} |`);
  lines.push(`| Resolved/Closed | ${closed} |`);
  lines.push(`| Avg resolution time | ${avgResolDays !== null ? avgResolDays + ' days' : '—'} |`);
  lines.push(`| Overdue (>30d open) | ${overdue.length} |`);
  lines.push(`| Oldest open request | ${oldestDays !== null ? oldestDays + ' days' : '—'} |`);
  lines.push(`| Total commitments tracked | ${totalCommitments} |`);
  lines.push(`| Open commitments | ${openCommitments} |`);
  lines.push('');
  // ── Section 5: New permits this week ──
  lines.push('## 🏗️ New Permits This Week');
  try {
    const newPermits = db.prepare(`
      SELECT permit_no, permit_type, work_description, address, status, applied_date, estimated_value
      FROM permits
      WHERE applied_date >= ?
      ORDER BY applied_date DESC
    `).all(weekAgo);

    if (newPermits.length === 0) {
      lines.push('No new permits applied for in the past 7 days.');
    } else {
      lines.push(`${newPermits.length} permit(s) applied since ${weekAgo}:`);
      lines.push('');
      const byType = groupBy(newPermits, 'permit_type');
      for (const [type, count] of byType) {
        lines.push(`- **${type}**: ${count}`);
      }
      lines.push('');
      for (const p of newPermits.slice(0, 10)) {
        const val = p.estimated_value ? ` ($${Number(p.estimated_value).toLocaleString()})` : '';
        lines.push(`  - [${formatDate(p.applied_date)}] ${p.permit_type || 'Unknown type'} — ${p.address || '?'}${val} (${p.status || '?'})`);
        if (p.work_description) lines.push(`    _${p.work_description.slice(0, 120)}_`);
      }
    }

    // All-time permit summary
    const totalPermits = db.prepare('SELECT COUNT(*) AS n FROM permits').get().n;
    if (totalPermits > 0) {
      lines.push('');
      lines.push(`_Total permits on file: ${totalPermits}_`);
    }
  } catch (e) {
    lines.push('_(permits table not yet populated — run fetch-all.js + ingest-all.js)_');
  }
  lines.push('');

  // ── Section 6: Open property violations ──
  lines.push('## 🚨 Open Property Violations');
  try {
    const violations = db.prepare(`
      SELECT case_no, violation_code, violation_description, address, neighborhood, status, opened_date
      FROM property_violations
      WHERE status NOT IN ('Closed','closed','CLOSED','Resolved','resolved') OR status IS NULL
      ORDER BY opened_date DESC
      LIMIT 100
    `).all();

    const totalViol = db.prepare('SELECT COUNT(*) AS n FROM property_violations').get().n;
    if (violations.length === 0) {
      lines.push(`No open property violations found. (${totalViol} total on file)`);
    } else {
      lines.push(`${violations.length} open violation(s) (${totalViol} total on file):`);
      lines.push('');
      const byCode = groupBy(violations, 'violation_code');
      for (const [code, count] of byCode.slice(0, 8)) {
        lines.push(`- **${code}**: ${count}`);
      }
      lines.push('');
      lines.push('Most recent:');
      for (const v of violations.slice(0, 8)) {
        const desc = v.violation_description || v.violation_code || 'Unknown';
        lines.push(`  - [${formatDate(v.opened_date)}] ${desc} — ${v.address || '?'} (${v.status || 'Open'})`);
      }
    }
  } catch (e) {
    lines.push('_(violations table not yet populated — run fetch-all.js + ingest-all.js)_');
  }
  lines.push('');

  // ── Section 7: Dangerous buildings ──
  lines.push('## 🏚️ Dangerous / Unsafe Buildings');
  try {
    const buildings = db.prepare(`
      SELECT case_number, address, neighborhood, status, case_opened
      FROM dangerous_buildings
      ORDER BY case_opened DESC
    `).all();

    if (buildings.length === 0) {
      lines.push('No dangerous buildings on file.');
    } else {
      lines.push(`${buildings.length} dangerous building case(s) on file:`);
      lines.push('');
      const byStatus = groupBy(buildings, 'status');
      for (const [s, count] of byStatus) {
        lines.push(`- **${s}**: ${count}`);
      }
      lines.push('');
      // Flag any opened or changed this week
      const recentBuildings = buildings.filter(b => b.case_opened && b.case_opened >= weekAgo);
      if (recentBuildings.length) {
        lines.push(`⚠️ New this week (${recentBuildings.length}):`);
        for (const b of recentBuildings) {
          lines.push(`  - [${formatDate(b.case_opened)}] ${b.address || '?'} — ${b.status || '?'}`);
        }
      } else {
        lines.push('No new dangerous building cases this week.');
        lines.push('');
        lines.push('Active cases:');
        for (const b of buildings.filter(b => b.status && !b.status.toLowerCase().includes('close')).slice(0, 5)) {
          lines.push(`  - [${formatDate(b.case_opened)}] ${b.address || '?'} — ${b.status}`);
        }
      }
    }
  } catch (e) {
    lines.push('_(dangerous_buildings table not yet populated — run fetch-all.js + ingest-all.js)_');
  }
  lines.push('');

  // ── Section 8: Budget context ──
  lines.push('## 💰 Budget Context (Parks + Public Works)');
  try {
    const budgetRows = db.prepare(`
      SELECT department, budget_type, SUM(amount) AS total
      FROM budget
      WHERE (lower(department) LIKE '%park%' OR lower(department) LIKE '%public work%'
             OR lower(department) LIKE '%nhs%' OR lower(department) LIKE '%neighborhood%')
      GROUP BY department, budget_type
      ORDER BY total DESC
    `).all();

    if (budgetRows.length === 0) {
      lines.push('_(budget table not yet populated — run fetch-all.js + ingest-all.js)_');
    } else {
      const totalBudget = db.prepare(`SELECT SUM(amount) AS t FROM budget WHERE budget_type='expenditure'`).get().t || 0;
      lines.push(`Total city expenditure budget on file: **$${Math.round(totalBudget).toLocaleString()}**`);
      lines.push('');
      lines.push('Relevant departments:');
      for (const row of budgetRows) {
        const sign = row.budget_type === 'revenue' ? '+' : '';
        lines.push(`  - ${row.department} (${row.budget_type}): **${sign}$${Math.round(row.total).toLocaleString()}**`);
      }
    }
  } catch (e) {
    lines.push('_(budget table not yet populated — run fetch-all.js + ingest-all.js)_');
  }
  lines.push('');

  // ── Section 9: Notable vendor payments ──
  lines.push('## 💳 Notable Vendor Payments (>$100K, Infrastructure/Construction)');
  try {
    const vendors = db.prepare(`
      SELECT vendor_name, department, amount, payment_date, description
      FROM vendor_payments
      WHERE amount >= 100000
        AND (lower(department) LIKE '%park%'
             OR lower(department) LIKE '%public work%'
             OR lower(department) LIKE '%nhs%'
             OR lower(department) LIKE '%neighborhood%'
             OR lower(description) LIKE '%construct%'
             OR lower(description) LIKE '%infrastructure%'
             OR lower(description) LIKE '%repair%'
             OR lower(description) LIKE '%paving%')
      ORDER BY amount DESC
      LIMIT 15
    `).all();

    if (vendors.length === 0) {
      // Try all large payments if department filter got nothing
      const allLarge = db.prepare(`
        SELECT vendor_name, department, amount, payment_date, description
        FROM vendor_payments
        WHERE amount >= 100000
        ORDER BY amount DESC
        LIMIT 10
      `).all();

      if (allLarge.length === 0) {
        lines.push('_(vendor_payments table not yet populated — run fetch-all.js + ingest-all.js)_');
      } else {
        lines.push('Largest payments (all departments):');
        for (const v of allLarge) {
          const desc = v.description ? ` — _${v.description.slice(0, 80)}_` : '';
          lines.push(`  - **$${Math.round(v.amount).toLocaleString()}** → ${v.vendor_name || '?'} (${v.department || '?'}) [${formatDate(v.payment_date)}]${desc}`);
        }
      }
    } else {
      for (const v of vendors) {
        const desc = v.description ? ` — _${v.description.slice(0, 80)}_` : '';
        lines.push(`  - **$${Math.round(v.amount).toLocaleString()}** → ${v.vendor_name || '?'} (${v.department || '?'}) [${formatDate(v.payment_date)}]${desc}`);
      }
    }
  } catch (e) {
    lines.push('_(vendor_payments table not yet populated — run fetch-all.js + ingest-all.js)_');
  }
  lines.push('');

  lines.push(`---`);
  lines.push(`*Generated ${new Date().toLocaleString('en-US', { timeZone: 'America/Chicago' })} CT*`);

  return lines.join('\n');
}

function main() {
  const db = getDb();

  // Check if we have data
  const count = db.prepare('SELECT COUNT(*) AS n FROM requests_311').get().n;
  if (count === 0) {
    console.log('No 311 data in DB yet. Run "node fetch-311.js" then "node ingest.js" first.');
  }

  const digest = buildDigest(db);

  // Print to stdout
  console.log(digest);

  // Save to digests/
  const digestDir = path.join(__dirname, 'digests');
  if (!fs.existsSync(digestDir)) fs.mkdirSync(digestDir, { recursive: true });

  const filename = path.join(digestDir, `${today()}.md`);
  fs.writeFileSync(filename, digest, 'utf8');
  console.log(`\n[Saved to ${filename}]`);

  // Log to DB
  db.prepare('INSERT INTO digest_log (summary_text) VALUES (?)').run(digest.slice(0, 2000));

  db.close();
}

main();
